# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('url', models.CharField(blank=True, default=b'', max_length=300)),
            ],
        ),
    ]
