# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_complementarymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementarymaterial',
            name='material_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=videos.models.get_material_path),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compementary_materials', to='videos.Video'),
        ),
    ]
