# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20170417_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complementarymaterial',
            old_name='name',
            new_name='title',
        ),
    ]
