# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20170423_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementarymaterial',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complementary_materials', to='videos.Video'),
        ),
    ]
