# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20170423_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
    ]
