# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20170913_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='categories.Professor'),
        ),
    ]
