# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='address_number',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='street',
        ),
    ]
