# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20170430_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moip_id', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('first_six', models.CharField(max_length=6)),
                ('last_four', models.CharField(max_length=4)),
                ('card_name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='address_no',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='asaas_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='postal_code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
