# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='first_six',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='moip_id',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='asaas_token',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.CreditCard'),
        ),
    ]
