# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='address_no',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
