# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20171107_1735'),
        ('payments', '0009_auto_20171107_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
