# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.CreditCard'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
