# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20171123_0336'),
        ('payments', '0011_auto_20171110_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='promocode',
            name='percentage',
            field=models.BooleanField(default=True),
        ),
    ]
