# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_promocode_one_time_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=payments.models.create_promo_code, max_length=12, unique=True),
        ),
    ]
