# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20180314_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
