# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_type',
            field=models.CharField(choices=[('C', 'Course'), ('S', 'Slide Collection')], default='C', max_length=30),
        ),
    ]
