# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:43
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=image_cropping.fields.ImageCropField(blank=True, default='profiledefault.jpg', upload_to=users.models.get_image_path),
        ),
    ]
