# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170327_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='course_hours',
            field=models.IntegerField(default=0),
        ),
    ]
