# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
    ]
