# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171107_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
