# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180622_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='email address'),
        ),
    ]
