# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='CourseTest',
        ),
    ]
