# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0002_auto_20170402_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together=set([('question', 'correct')]),
        ),
    ]
