# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0003_auto_20170402_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct',
            new_name='answered_correctly',
        ),
    ]
