# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0004_auto_20170402_0332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together=set([]),
        ),
    ]
