# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursetests', '0005_auto_20170402_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('answered_correctly', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answered_correctly',
        ),
        migrations.AddField(
            model_name='userquestionrelationship',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursetests.Question'),
        ),
        migrations.AddField(
            model_name='userquestionrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(related_name='questions', through='coursetests.UserQuestionRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
