# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0006_auto_20170402_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
