# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0007_auto_20170403_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(related_name='questions', through='coursetests.UserQuestionRelationship', to='users.MyUser'),
        ),
        migrations.AlterField(
            model_name='userquestionrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
        ),
    ]
