# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0008_auto_20170518_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetest',
            options={'verbose_name': 'Teste', 'verbose_name_plural': 'Testes'},
        ),
        migrations.AddField(
            model_name='coursetest',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
