# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0009_auto_20170802_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetest',
            options={'ordering': ['title'], 'verbose_name': 'Teste', 'verbose_name_plural': 'Testes'},
        ),
    ]
