# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0010_auto_20170913_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'Quest\xe3o', 'verbose_name_plural': 'Quest\xf5es'},
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect',
            field=models.BooleanField(default=False),
        ),
    ]
