# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0012_auto_20180820_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('correct', 'correta'), ('incorrect', 'incorreta'), ('tof', 'V ou F')], default='correct', max_length=15),
        ),
    ]
