# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
