# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20170411_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='name',
            new_name='title',
        ),
    ]
