# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20170411_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Leitura', 'verbose_name_plural': 'Leituras'},
        ),
    ]
