# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20170909_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['title'], 'verbose_name': 'Leitura', 'verbose_name_plural': 'Leituras'},
        ),
    ]
