# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20170320_0036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together=set([('category', 'position')]),
        ),
    ]
