# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20170320_0245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together=set([]),
        ),
    ]
