# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20170320_0036'),
        ('courses', '0005_remove_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='categories.Professor'),
        ),
    ]
