# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseitem',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='courseitem',
            unique_together=set([('course', 'position')]),
        ),
    ]
