# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20170327_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='videos.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='courseitem',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='useritemrelationship',
            name='course_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseItem'),
        ),
        migrations.AddField(
            model_name='useritemrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='users',
            field=models.ManyToManyField(related_name='course_items', through='courses.UserItemRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
