# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_usercourserelationship_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', through='courses.UserCourseRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
