# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170331_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemrelationship',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
