# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20170401_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
