# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20170402_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourserelationship',
            old_name='percentage',
            new_name='correct_answers',
        ),
        migrations.AddField(
            model_name='usercourserelationship',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
    ]
