# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20170402_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemrelationship',
            name='answered_correctly',
            field=models.BooleanField(default=False),
        ),
    ]
