# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_useritemrelationship_answered_correctly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='test',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_item', to='coursetests.CourseTest'),
        ),
    ]
