# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20170402_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritemrelationship',
            name='answered_correctly',
        ),
    ]
