# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
        ('courses', '0024_remove_useritemrelationship_answered_correctly'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='reading',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.Reading'),
        ),
    ]
