# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20170411_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourserelationship',
            name='last_accessed_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseItem'),
        ),
    ]
