# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_usercourserelationship_last_accessed_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelationship',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rels', to='courses.Course'),
        ),
    ]
