# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20170506_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourserelationship',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
