# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_usercourserelationship_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourserelationship',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourserelationship',
            name='passing_grade',
            field=models.IntegerField(default=70),
        ),
    ]
