# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0031_auto_20170508_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('course_name', models.CharField(max_length=150)),
                ('course_hours', models.IntegerField()),
                ('identifier', models.CharField(default=shortuuid.main.uuid, max_length=150, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercourserelationship',
            name='certificate',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_rel', to='courses.Certificate'),
        ),
    ]
