# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:13
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20170518_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='identifier',
            field=models.CharField(default=courses.models.certificate_identifier, max_length=150, primary_key=True, serialize=False),
        ),
    ]
