# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 11:33
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20170605_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='logodefault.png', upload_to=courses.models.get_thumbnail_path),
        ),
    ]
