# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20170605_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
