# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 18:33
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_course_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='courseitem',
            options={'verbose_name': 'Passo do Curso', 'verbose_name_plural': 'Passos do Curso'},
        ),
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas do Curso'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='logodefault.png', upload_to=courses.models.get_thumbnail_path),
        ),
    ]
