# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20171106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelationship',
            name='passing_grade',
            field=models.IntegerField(default=60),
        ),
    ]
