# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 01:11
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20171107_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='readings_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=courses.models.get_extra_materials_path),
        ),
        migrations.AddField(
            model_name='course',
            name='slides_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=courses.models.get_slides_path),
        ),
    ]
