# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20171121_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelationship',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usercourserelationship',
            name='last_accessed_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseItem'),
        ),
    ]
