# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20171123_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelationship',
            name='passing_grade',
            field=models.IntegerField(default=50),
        ),
    ]
