# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20180806_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelationship',
            name='certificate',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_rel', to='courses.Certificate'),
        ),
    ]
